# Generated by Django 4.1.3 on 2022-11-16 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_card_card_msg_card_color_card_font_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='color',
            field=models.CharField(choices=[('ORANGE', 'ORANGE'), ('PURPLE', 'PURPLE'), ('GRAY', 'GRAY'), ('GOLD', 'GOLD'), ('YELLOW', 'YELLOW'), ('GREEN', 'GREEN'), ('BLACK', 'BLACK'), ('BLUE', 'BLUE'), ('RED', 'RED'), ('DARKRED', 'DARKRED')], default='WHITE', max_length=50),
        ),
        migrations.AlterField(
            model_name='card',
            name='font_color',
            field=models.CharField(choices=[('ORANGE', 'ORANGE'), ('PURPLE', 'PURPLE'), ('GRAY', 'GRAY'), ('GOLD', 'GOLD'), ('YELLOW', 'YELLOW'), ('GREEN', 'GREEN'), ('BLACK', 'BLACK'), ('BLUE', 'BLUE'), ('RED', 'RED'), ('DARKRED', 'DARKRED')], default='BLACK', max_length=50),
        ),
    ]
