# Generated by Django 4.1.3 on 2022-11-17 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_card_color_alter_card_font_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='color',
            field=models.CharField(choices=[('ORANGE', 'ORANGE'), ('RED', 'RED'), ('BLACK', 'BLACK'), ('GREEN', 'GREEN'), ('DARKRED', 'DARKRED'), ('YELLOW', 'YELLOW'), ('BLUE', 'BLUE'), ('GOLD', 'GOLD'), ('PURPLE', 'PURPLE'), ('GRAY', 'GRAY')], default='WHITE', max_length=50),
        ),
        migrations.AlterField(
            model_name='card',
            name='font_color',
            field=models.CharField(choices=[('ORANGE', 'ORANGE'), ('RED', 'RED'), ('BLACK', 'BLACK'), ('GREEN', 'GREEN'), ('DARKRED', 'DARKRED'), ('YELLOW', 'YELLOW'), ('BLUE', 'BLUE'), ('GOLD', 'GOLD'), ('PURPLE', 'PURPLE'), ('GRAY', 'GRAY')], default='BLACK', max_length=50),
        ),
    ]
