# Generated by Django 4.1.3 on 2022-11-17 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_card_color_alter_card_font_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='color',
            field=models.CharField(choices=[('GOLD', 'GOLD'), ('DARKRED', 'DARKRED'), ('GRAY', 'GRAY'), ('PURPLE', 'PURPLE'), ('RED', 'RED'), ('BLUE', 'BLUE'), ('ORANGE', 'ORANGE'), ('YELLOW', 'YELLOW'), ('BLACK', 'BLACK'), ('GREEN', 'GREEN')], default='WHITE', max_length=50),
        ),
        migrations.AlterField(
            model_name='card',
            name='font_color',
            field=models.CharField(choices=[('GOLD', 'GOLD'), ('DARKRED', 'DARKRED'), ('GRAY', 'GRAY'), ('PURPLE', 'PURPLE'), ('RED', 'RED'), ('BLUE', 'BLUE'), ('ORANGE', 'ORANGE'), ('YELLOW', 'YELLOW'), ('BLACK', 'BLACK'), ('GREEN', 'GREEN')], default='BLACK', max_length=50),
        ),
    ]
