# Generated by Django 4.1.3 on 2022-11-17 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_card_color_alter_card_font_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='color',
            field=models.CharField(choices=[('GRAY', 'GRAY'), ('YELLOW', 'YELLOW'), ('RED', 'RED'), ('BLUE', 'BLUE'), ('BLACK', 'BLACK'), ('DARKRED', 'DARKRED'), ('GREEN', 'GREEN'), ('GOLD', 'GOLD'), ('ORANGE', 'ORANGE'), ('PURPLE', 'PURPLE')], default='WHITE', max_length=50),
        ),
        migrations.AlterField(
            model_name='card',
            name='font_color',
            field=models.CharField(choices=[('GRAY', 'GRAY'), ('YELLOW', 'YELLOW'), ('RED', 'RED'), ('BLUE', 'BLUE'), ('BLACK', 'BLACK'), ('DARKRED', 'DARKRED'), ('GREEN', 'GREEN'), ('GOLD', 'GOLD'), ('ORANGE', 'ORANGE'), ('PURPLE', 'PURPLE')], default='BLACK', max_length=50),
        ),
    ]
