# Generated by Django 4.1.3 on 2022-11-17 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_card_color_alter_card_font_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='color',
            field=models.CharField(choices=[('GREEN', 'GREEN'), ('DARKRED', 'DARKRED'), ('BLUE', 'BLUE'), ('YELLOW', 'YELLOW'), ('BLACK', 'BLACK'), ('PURPLE', 'PURPLE'), ('GRAY', 'GRAY'), ('ORANGE', 'ORANGE'), ('GOLD', 'GOLD'), ('RED', 'RED')], default='WHITE', max_length=50),
        ),
        migrations.AlterField(
            model_name='card',
            name='font_color',
            field=models.CharField(choices=[('GREEN', 'GREEN'), ('DARKRED', 'DARKRED'), ('BLUE', 'BLUE'), ('YELLOW', 'YELLOW'), ('BLACK', 'BLACK'), ('PURPLE', 'PURPLE'), ('GRAY', 'GRAY'), ('ORANGE', 'ORANGE'), ('GOLD', 'GOLD'), ('RED', 'RED')], default='BLACK', max_length=50),
        ),
    ]
