git# Generated by Django 4.1.3 on 2022-11-17 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_card_color_alter_card_font_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='color',
            field=models.CharField(choices=[('YELLOW', 'YELLOW'), ('ORANGE', 'ORANGE'), ('GREEN', 'GREEN'), ('BLUE', 'BLUE'), ('GRAY', 'GRAY'), ('PURPLE', 'PURPLE'), ('RED', 'RED'), ('GOLD', 'GOLD'), ('BLACK', 'BLACK'), ('DARKRED', 'DARKRED')], default='WHITE', max_length=50),
        ),
        migrations.AlterField(
            model_name='card',
            name='font_color',
            field=models.CharField(choices=[('YELLOW', 'YELLOW'), ('ORANGE', 'ORANGE'), ('GREEN', 'GREEN'), ('BLUE', 'BLUE'), ('GRAY', 'GRAY'), ('PURPLE', 'PURPLE'), ('RED', 'RED'), ('GOLD', 'GOLD'), ('BLACK', 'BLACK'), ('DARKRED', 'DARKRED')], default='BLACK', max_length=50),
        ),
    ]
