# Generated by Django 4.1.3 on 2022-11-22 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_card_color_alter_card_font_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='color',
            field=models.CharField(choices=[('GRAY', 'GRAY'), ('GREEN', 'GREEN'), ('DARKRED', 'DARKRED'), ('ORANGE', 'ORANGE'), ('BLUE', 'BLUE'), ('RED', 'RED'), ('PURPLE', 'PURPLE'), ('YELLOW', 'YELLOW'), ('GOLD', 'GOLD'), ('BLACK', 'BLACK')], default='WHITE', max_length=50),
        ),
        migrations.AlterField(
            model_name='card',
            name='font_color',
            field=models.CharField(choices=[('GRAY', 'GRAY'), ('GREEN', 'GREEN'), ('DARKRED', 'DARKRED'), ('ORANGE', 'ORANGE'), ('BLUE', 'BLUE'), ('RED', 'RED'), ('PURPLE', 'PURPLE'), ('YELLOW', 'YELLOW'), ('GOLD', 'GOLD'), ('BLACK', 'BLACK')], default='BLACK', max_length=50),
        ),
    ]
