# Generated by Django 4.1.3 on 2022-11-22 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_card_color_alter_card_font_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='color',
            field=models.CharField(choices=[('PURPLE', 'PURPLE'), ('BLUE', 'BLUE'), ('GRAY', 'GRAY'), ('ORANGE', 'ORANGE'), ('GOLD', 'GOLD'), ('DARKRED', 'DARKRED'), ('GREEN', 'GREEN'), ('RED', 'RED'), ('YELLOW', 'YELLOW'), ('BLACK', 'BLACK')], default='WHITE', max_length=50),
        ),
        migrations.AlterField(
            model_name='card',
            name='font_color',
            field=models.CharField(choices=[('PURPLE', 'PURPLE'), ('BLUE', 'BLUE'), ('GRAY', 'GRAY'), ('ORANGE', 'ORANGE'), ('GOLD', 'GOLD'), ('DARKRED', 'DARKRED'), ('GREEN', 'GREEN'), ('RED', 'RED'), ('YELLOW', 'YELLOW'), ('BLACK', 'BLACK')], default='BLACK', max_length=50),
        ),
    ]
