# Generated by Django 4.1.3 on 2022-11-29 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_card_color_alter_card_font_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='text_alignment',
            field=models.CharField(choices=[('CENTER', 'CENTER'), ('RIGHT', 'RIGHT'), ('LEFT', 'LEFT')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
