# Generated by Django 4.1.3 on 2022-11-22 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_card_color_alter_card_font_color'),
        ('core', '0015_card_text_alignment')
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='color',
            field=models.CharField(choices=[('DARKRED', 'DARKRED'), ('BLACK', 'BLACK'), ('GREEN', 'GREEN'), ('BLUE', 'BLUE'), ('ORANGE', 'ORANGE'), ('YELLOW', 'YELLOW'), ('PURPLE', 'PURPLE'), ('RED', 'RED'), ('GOLD', 'GOLD'), ('GRAY', 'GRAY')], default='WHITE', max_length=50),
        ),
        migrations.AlterField(
            model_name='card',
            name='font_color',
            field=models.CharField(choices=[('DARKRED', 'DARKRED'), ('BLACK', 'BLACK'), ('GREEN', 'GREEN'), ('BLUE', 'BLUE'), ('ORANGE', 'ORANGE'), ('YELLOW', 'YELLOW'), ('PURPLE', 'PURPLE'), ('RED', 'RED'), ('GOLD', 'GOLD'), ('GRAY', 'GRAY')], default='BLACK', max_length=50),
        ),
    ]
