# Generated by Django 4.1.3 on 2022-11-22 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_card_color_alter_card_font_color'),
        ('core', '0016_comment')
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='color',
            field=models.CharField(choices=[('GRAY', 'GRAY'), ('BLUE', 'BLUE'), ('GOLD', 'GOLD'), ('BLACK', 'BLACK'), ('ORANGE', 'ORANGE'), ('YELLOW', 'YELLOW'), ('GREEN', 'GREEN'), ('RED', 'RED'), ('DARKRED', 'DARKRED'), ('PURPLE', 'PURPLE')], default='WHITE', max_length=50),
        ),
        migrations.AlterField(
            model_name='card',
            name='font_color',
            field=models.CharField(choices=[('GRAY', 'GRAY'), ('BLUE', 'BLUE'), ('GOLD', 'GOLD'), ('BLACK', 'BLACK'), ('ORANGE', 'ORANGE'), ('YELLOW', 'YELLOW'), ('GREEN', 'GREEN'), ('RED', 'RED'), ('DARKRED', 'DARKRED'), ('PURPLE', 'PURPLE')], default='BLACK', max_length=50),
        ),
    ]
