# Generated by Django 4.1.3 on 2022-11-29 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_comment'),
        
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='text_alignment',
            field=models.CharField(choices=[('CENTER', 'CENTER'), ('RIGHT', 'RIGHT'), ('LEFT', 'LEFT')], default='LEFT', max_length=50),
        ),
    ]
