# Generated by Django 4.1.3 on 2022-11-30 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_card_color_alter_card_font_color_and_more'),
        ('core', '0017_alter_card_text_alignment'),
    ]

    operations = [
    ]
