# Generated by Django 4.1.3 on 2022-11-30 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_card_color_alter_card_font_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.TextField(default='nick', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.TextField(default='password', max_length=300),
            preserve_default=False,
        ),
    ]
