# Generated by Django 4.1.3 on 2022-11-30 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_comment'),
        ('core', '0017_alter_card_color_alter_card_font_color_and_more'),
    ]

    operations = [
    ]
