# Generated by Django 4.1.3 on 2022-11-30 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_card_text_alignment'),
        ('core', '0018_merge_20221130_1940'),
    ]

    operations = [
    ]
