# Generated by Django 4.1.3 on 2022-11-30 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_card_color_alter_card_font_color_and_more'),
        ('core', '0018_alter_user_name_alter_user_password'),
    ]

    operations = [
    ]
